pipeline {
    agent {
        label 'docker'
    }
    
    stages {
        stage('Setup') {
            steps {
                echo 'Setup'
                sh "git clean -dfx"
                sh "docker image build -t rvgpu/sphinx:latest .ci/"
            }
        }

        stage('Build Html') {
            steps {
                echo "Build docs on docker"
                sh 'docker run --rm -v .:/docs -u $(id -u):$(id -g) rvgpu/sphinx clean'
                sh 'docker run --rm -v .:/docs -u $(id -u):$(id -g) rvgpu/sphinx'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploy html to github repos"
                dir ("_build/html/") {
                    sh 'touch .nojekyll'
                    sh 'git init'
                    sh 'git add . '
                    sh 'git commit -m "push to github pages"'
                    sh 'git remote add origin https://github.com/rvgpu/rvgpu.github.io.git'
                    withCredentials([gitUsernamePassword(credentialsId: 'GITHUB_ACCESS_TOKEN', gitToolName: 'Default')]) {
                        sh 'git push origin main --force'
                    }
                }
            }
        }
    }
}

