pipeline {
    agent {
        label 'docker'
    }
    
    stages {
        stage('Setup') {
            steps {
                echo 'Setup'
                sh "git clean -dfx"
                sh "rm -rf _build/*"
                sh "rm -rf pages"
                sh "docker image build -t rvgpu/sphinx:latest .ci/"
            }
        }

        stage('Build Html') {
            steps {
                echo "Build docs on docker"
                sh 'docker run --rm -v .:/docs -u $(id -u):$(id -g) rvgpu/sphinx clean'
                sh 'docker run --rm -v .:/docs -u $(id -u):$(id -g) rvgpu/sphinx'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploy html to github repos"
                sh 'git clone https://gitee.com/rvgpu/pages.git'
                sh 'cp -r _build/html/* pages/'
                dir ("pages") {
                    script {
                        echo "check the pages repo status"
                        def gitStatus = sh(script: 'git status --porcelain', returnStdout: true).trim()
                        if (gitStatus) {
                            sh 'git add .'
                            sh 'git commit -m "Push to GitHub Pages with Jenkins"'
                        }
                        echo "end of script"
                    }

                    withCredentials([gitUsernamePassword(credentialsId: 'bf57e642-4a3f-4214-be2c-2948cb6bfd60', gitToolName: 'Default')]) {
                        sh 'git push origin master'
                    }
                }

                sh 'rm -rf _build/*'
                sh 'rm -rf pages'
            }
        }
    }
}

